In [ ]:
import pandas as pd

ratings = pd.read_csv(
    "u.data", sep="\t", names=["userId", "movieId", "rating", "timestamp"]
)

ratings

       userId  movieId  rating  timestamp
0         196      242       3  881250949
1         186      302       3  891717742
2          22      377       1  878887116
3         244       51       2  880606923
4         166      346       1  886397596
...       ...      ...     ...        ...
99995     880      476       3  880175444
99996     716      204       5  879795543
99997     276     1090       1  874795795
99998      13      225       2  882399156
99999      12      203       3  879959583

[100000 rows x 4 columns]

In [ ]:
movies = pd.read_csv(
    "u.item",
    sep="|",
    encoding="latin-1",
    names=[
        "movieId",
        "title",
        "releaseDate",
        "videoReleaseDate",
        "IMDbURL",
        "genreUnknow",
        "genreAction",
        "genreAdventure",
        "genreAnimation",
        "genreChildren",
        "genreComedy",
        "genreCrime",
        "genreDocumentary",
        "genreDrama",
        "genreFantasy",
        "genreFilmNoir",
        "genreHorror",
        "genreMusical",
        "genreMystery",
        "genreRomance",
        "genreSciFi",
        "genreThriller",
        "genreWar",
        "genreWestern",
    ],
)

movies.head()

,movieId,title,releaseDate,videoReleaseDate,IMDbURL,genreUnknow,genreAction,genreAdventure,genreAnimation,genreChildren,...,genreFantasy,genreFilmNoir,genreHorror,genreMusical,genreMystery,genreRomance,genreSciFi,genreThriller,genreWar,genreWestern
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0