In [23]:
import pandas as pd

ratings = pd.read_csv(
    "u.data", sep="\t", names=["userId", "movieId", "rating", "timestamp"]
)

ratings

       userId  movieId  rating  timestamp
0         196      242       3  881250949
1         186      302       3  891717742
2          22      377       1  878887116
3         244       51       2  880606923
4         166      346       1  886397596
...       ...      ...     ...        ...
99995     880      476       3  880175444
99996     716      204       5  879795543
99997     276     1090       1  874795795
99998      13      225       2  882399156
99999      12      203       3  879959583

[100000 rows x 4 columns]

In [24]:
movies = pd.read_csv(
    "u.item",
    sep="|",
    encoding="latin-1",
    names=[
        "movieId",
        "title",
        "releaseDate",
        "videoReleaseDate",
        "IMDbURL",
        "genreUnknow",
        "genreAction",
        "genreAdventure",
        "genreAnimation",
        "genreChildren",
        "genreComedy",
        "genreCrime",
        "genreDocumentary",
        "genreDrama",
        "genreFantasy",
        "genreFilmNoir",
        "genreHorror",
        "genreMusical",
        "genreMystery",
        "genreRomance",
        "genreSciFi",
        "genreThriller",
        "genreWar",
        "genreWestern",
    ],
)

movies

,movieId,title,releaseDate,videoReleaseDate,IMDbURL,genreUnknow,genreAction,genreAdventure,genreAnimation,genreChildren,...,genreFantasy,genreFilmNoir,genreHorror,genreMusical,genreMystery,genreRomance,genreSciFi,genreThriller,genreWar,genreWestern
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
data = ratings.merge(movies[["movieId", "title"]], on="movieId", how="left")
data

       userId  movieId  rating  timestamp                         title
0         196      242       3  881250949                  Kolya (1996)
1         186      302       3  891717742      L.A. Confidential (1997)
2          22      377       1  878887116           Heavyweights (1994)
3         244       51       2  880606923    Legends of the Fall (1994)
4         166      346       1  886397596           Jackie Brown (1997)
...       ...      ...     ...        ...                           ...
99995     880      476       3  880175444  First Wives Club, The (1996)
99996     716      204       5  879795543     Back to the Future (1985)
99997     276     1090       1  874795795                 Sliver (1993)
99998      13      225       2  882399156         101 Dalmatians (1996)
99999      12      203       3  879959583             Unforgiven (1992)

[100000 rows x 5 columns]

In [26]:
data["title"].isna().sum()

np.int64(0)

In [27]:
client_data = pd.pivot_table(
    data=data, values="rating", index="userId", columns="title", fill_value=0
)
client_data

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,2.0,5.0,0.0,0.0,3.0,4.0,0.0,0.0,...,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0,0.0

On va faire notre modéle de machone learning à partir de ce jeu de donnée. Pour analyser ce je ude donnée on va d'abords faire une réduction de dimension. Comme toutes les colonnes sont de même échelle on peut utiliser une analyse en composante principale directement sans standardisation.

In [28]:
from sklearn.decomposition import PCA
from sklearn import set_config

set_config(transform_output="pandas")

pca = PCA(n_components=3)

red_data = pca.fit_transform(client_data)
red_data

             pca0       pca1       pca2
userId
1       27.101136   1.725024   5.090572
2      -10.419712   0.518710   9.482474
3      -13.227436  -0.289544   0.532231
4      -12.556222   0.112788  -2.181874
5        7.614065   3.741099 -10.700032
...           ...        ...        ...
939     -9.583462   5.870914   3.201618
940      2.034060  -3.416143   2.205542
941    -11.349007   2.162016  -0.585607
942     -0.526092  -6.079199  -4.137621
943     13.375018  10.408605  -5.622859

[943 rows x 3 columns]

In [29]:
import seaborn as sns
import plotly.express as px

fig = px.scatter_3d(red_data, x="pca0", y="pca1", z="pca2", size_max=18)
fig.update_traces(marker_size=3)
fig.show()

On observe qu'il n'y a pas vraiment de groupes de client différents mais qu'il y a une zone dans lequel il y a beaucoup de clients qui sont proche puis plus on s'éloigne selon les trois composante principale, les clients sont de moins en moins proche. Essayons de voir si une autres méthodes de réduction de dimension peut nous montrer des cluster distinct. Essayons le tsne.

In [30]:
from sklearn.manifold import TSNE

red_data = TSNE(n_components=3, perplexity=40).fit_transform(client_data)
red_data

            tsne0      tsne1      tsne2
userId
1       61.077614  19.523836  -2.105953
2      -52.698040  26.899630 -21.387707
3      -49.004570 -18.546326  14.718776
4      -17.178934  12.451416 -19.529705
5       29.948223  31.593994   9.704136
...           ...        ...        ...
939      0.171866 -21.992294  39.937954
940    -29.643253 -34.856289 -37.725361
941    -11.819465  13.204742  23.230129
942    -42.424843 -38.338428  -4.667183
943     51.644512  -0.104488  41.832432

[943 rows x 3 columns]

On voit que le tsne ne révéle aucun cluster. Testons la méthode ISOMAP avec la métrique cosinus.

In [31]:
fig = px.scatter_3d(red_data, x="tsne0", y="tsne1", z="tsne2")
fig.update_traces(marker_size=3)
fig.show()

In [ ]:
from sklearn.manifold import Isomap

red_data = Isomap(n_components=3, n_neighbors=3, metric="cosine").fit_transform(
    client_data
)
red_data

         isomap0   isomap1   isomap2
userId
1      -1.334380 -0.069460  0.526080
2       1.419339 -0.772273 -0.662679
3       2.088613  1.181122  0.232003
4       1.550648  1.190672  0.785769
5      -1.391353  0.290591  0.777847
...          ...       ...       ...
939     1.135965 -1.575965 -0.213872
940    -0.708722  0.694212 -0.096437
941     1.416969 -1.386585  0.586579
942    -0.809223  0.929452 -0.105306
943    -1.121310 -0.178421  0.642923

[943 rows x 3 columns]

In [55]:
fig = px.scatter_3d(red_data, x="isomap0", y="isomap1", z="isomap2")
fig.update_traces(marker_size=3)
fig.show()

La méthode Isomap nous permet de voir qu'il y a selon la métrique cosinus trois cluster de client.